from PIL import Image, ImageFilter

img = Image.open('./astro.jpg')
# new_img = img.resize((400, 400))
img.thumbnail((400, 400))
img.save("thumbnail.jpg")
print(img.size)
# filtered_img = img.convert('L')
# print(img.format)
# print(img.size)
# print(img.mode)
# print(dir(img))
# crooked = filtered_img.rotate(0)
# crooked.save("grey.png", 'png')
# filtered_img.show()
# resize = filtered_img.resize((300, 300))
# resize.save("grey.png", 'png')
# box = (100, 100, 400, 400)
# region = filtered_img.crop(box)
# region.save("grey.png", 'png')
